export const languageDropdown = [
{label:"Arabic",value:"ar"},
{label:"Basque",value:	"eu"},
{label:"Bulgarian",value:	"bg"},
{label:"Catalan",value:	"ca"},
{label:"Chinese (Simplified)"	,value:"zh-CN"},
{label:"Chinese (Traditional)",value:	"zh-TW"},
{label:"Croatian",value:"hr"},
{label:"Czech",value:	"cs"},
{label:"Danish",value:	"da"},
{label:"Dutch",value:	"nl"},
{label:"English (Australia)",value:	"en-AU"},
{label:"English (Canada)",value:	"en-CA"},
{label:"English (India)",value:	"en-IN"},
{label:"English (New Zealand)",value:	"en-NZ"},
{label:"English (UK)",value:	"en-GB"},
{label:"English (US)",value:	"en-US"},
{label:"Estonian",value:	"et"},
{label:"Finnish",value:	"fi"},
{label:"French"	,value:"fr-FR"},
{label:"Galician",value:	"gl"},
{label:"German",value:	"de-DE"},
{label:"Greek",value:	"el"},
{label:"Gujarati",value:	"gu"},
{label:"Hebrew",value:	"he"},
{label:"Hindi"	,value:"hi"},
{label:"Hungarian"	,value:"hu"},
{label:"Icelandic"	,value:"is"},
{label:"Indonesian",value:	"id"},
{label:"Italian",value:	"it-IT"},
{label:"Japanese",value:	"ja-JP"},
{label:"Kannada",value:	"kn"},
{label:"Korean"	,value:"ko-KR"},
{label:"Latvian"	,value:"lv"},
{label:"Lithuanian",value:	"lt"},
{label:"Malay",value:	"ms"},
{label:"Malayalam",value:	"ml"},
{label:"Marathi",value:	"mr"},
{label:"Norwegian",value:	"nb"},
{label:"Persian"	,value:"fa"},
{label:"Polish",value:	"pl"},
{label:"Portuguese",value:	"pt-PT"},
{label:"Romanian",value:	"ro"},
{label:"Russian"	,value:"ru-RU"},
{label:"Serbian",value:	"sr"},
{label:"Slovak",value:	"sk"},
{label:"Slovenian",value:	"sl"},
{label:"Spanish"	,value:"es-ES"},
{label:"Spanish (Mexico)"	,value:"es-MX"},
{label:"Spanish (US)",value:	"es-US"},
{label:"Swahili",value:	"sw"},
{label:"Swedish"	,value:"sv-SE"},
{label:"Tamil",value:	"ta"},
{label:"Telugu"	,value:"te"},
{label:"Thai"	,value:"th"},
{label:"Turkish",value:	"tr-TR"},
{label:"Ukrainian",value:	"uk"},
{label:"Urdu",value:	"ur"},
{label:"Vietnamese",value:	"vi"},
]